[build]
  publish = "src"
  command = "echo 'No build step needed'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.gstatic.com https://js.razorpay.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
